[2024-08-28T15:10:56.100+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T15:10:56.109+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kubernetes_pod_operator_test.start_task manual__2024-08-28T15:10:53.962215+00:00 [queued]>
[2024-08-28T15:10:56.113+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kubernetes_pod_operator_test.start_task manual__2024-08-28T15:10:53.962215+00:00 [queued]>
[2024-08-28T15:10:56.114+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-28T15:10:56.121+0000] {taskinstance.py:2879} INFO - Executing <Task(KubernetesPodOperator): start_task> on 2024-08-28 15:10:53.962215+00:00
[2024-08-28T15:10:56.126+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T15:10:56.127+0000] {standard_task_runner.py:72} INFO - Started process 161 to run task
[2024-08-28T15:10:56.128+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kubernetes_pod_operator_test', 'start_task', 'manual__2024-08-28T15:10:53.962215+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/kubernetes_test_dap.py', '--cfg-path', '/tmp/tmpbidzjxv7']
[2024-08-28T15:10:56.128+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask start_task
[2024-08-28T15:10:56.156+0000] {task_command.py:467} INFO - Running <TaskInstance: kubernetes_pod_operator_test.start_task manual__2024-08-28T15:10:53.962215+00:00 [running]> on host 65aafae803e7
[2024-08-28T15:10:56.200+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kubernetes_pod_operator_test' AIRFLOW_CTX_TASK_ID='start_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T15:10:53.962215+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-28T15:10:53.962215+00:00'
[2024-08-28T15:10:56.201+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-28T15:10:56.201+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-28T15:10:56.202+0000] {logging_mixin.py:190} INFO - Current task name:start_task state:running start_date:2024-08-28 15:10:56.109674+00:00
[2024-08-28T15:10:56.202+0000] {logging_mixin.py:190} INFO - Dag name:kubernetes_pod_operator_test and current dag run status:running
[2024-08-28T15:10:56.202+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T15:10:56.206+0000] {pod.py:1132} INFO - Building pod ***-test-pod-8gy0olsy with labels: {'dag_id': 'kubernetes_pod_operator_test', 'task_id': 'start_task', 'run_id': 'manual__2024-08-28T151053.9622150000-320dc9b3f', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2024-08-28T15:10:56.213+0000] {base.py:84} INFO - Retrieving connection 'kubernetes_default'
[2024-08-28T15:10:56.214+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 592, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 600, in execute_sync
    self.pod_request_obj = self.build_pod_request_obj(context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 1141, in build_pod_request_obj
    "airflow_kpo_in_cluster": str(self.hook.is_in_cluster),
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 283, in is_in_cluster
    self.api_client  # so we can determine if we are in_cluster or not
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 291, in api_client
    return self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 233, in get_conn
    config.load_incluster_config()
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.
[2024-08-28T15:10:56.222+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-28T15:10:56.222+0000] {logging_mixin.py:190} INFO - Task start:2024-08-28 15:10:56.109674+00:00 end:2024-08-28 15:10:56.222146+00:00 duration:0.112472
[2024-08-28T15:10:56.223+0000] {logging_mixin.py:190} INFO - Task:<Task(KubernetesPodOperator): start_task> dag:<DAG: kubernetes_pod_operator_test> dagrun:<DagRun kubernetes_pod_operator_test @ 2024-08-28 15:10:53.962215+00:00: manual__2024-08-28T15:10:53.962215+00:00, state:running, queued_at: 2024-08-28 15:10:53.985735+00:00. externally triggered: True>
[2024-08-28T15:10:56.223+0000] {logging_mixin.py:190} INFO - Failure caused by Service host/port is not set.
[2024-08-28T15:10:56.223+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kubernetes_pod_operator_test, task_id=start_task, run_id=manual__2024-08-28T15:10:53.962215+00:00, execution_date=20240828T151053, start_date=20240828T151056, end_date=20240828T151056
[2024-08-28T15:10:56.232+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T15:10:56.233+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task start_task (Service host/port is not set.; 161)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 592, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 600, in execute_sync
    self.pod_request_obj = self.build_pod_request_obj(context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 1141, in build_pod_request_obj
    "airflow_kpo_in_cluster": str(self.hook.is_in_cluster),
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 283, in is_in_cluster
    self.api_client  # so we can determine if we are in_cluster or not
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 291, in api_client
    return self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 233, in get_conn
    config.load_incluster_config()
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.
[2024-08-28T15:10:56.261+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-28T15:10:56.270+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T15:10:56.271+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
